version: '3'
services:

  front:
    image: testfront
    command: npm run dev
    working_dir: /usr/src/app
    labels:
      - 'traefik.backend=frontend'
      - 'traefik.frontend.rule=Host:front.${HOST_URL}'
      - 'traefik.port=8080'
    volumes:
      - ./front:/usr/src/app
    env_file:
      - ./.env

  back:
    image: testback
    command: adonis serve --dev
    working_dir: /usr/src/app
    labels:
      - 'traefik.backend=backend'
      - 'traefik.frontend.rule=Host:back.${HOST_URL}'
      - 'traefik.port=8080'
    volumes:
      - ./back:/usr/src/app
    env_file:
      - ./.env

  mysql:
    image: testmysql
    labels:
      - 'traefik.enable=false'
    env_file:
      - ./.env

  traefik:
    command: '--docker --logLevel=DEBUG'
    image: traefik:1.7
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.frontend.rule=Host:traefik.${HOST_URL}'
      - 'traefik.port=8080'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/traefik.dev.toml:/traefik.toml:ro'
      - './traefik/acme.json:/acme.json:rw'

