defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "screlec.local"
watch = true
exposedbydefault = false

[web]  # Port for the status page
address = ":8080"
