FROM mysql:5.7

ADD ./dump/databases.sql /docker-entrypoint-initdb.d/01-dump.sql

ENV DB_USERNAME=formationnoobdocker
ENV DB_PASSWORD=apwnZOXN*
ENV MYSQL_ROOT_PASSWORD=apwnZOXN*
ENV MYSQL_USER=screlec
ENV MYSQL_PASSWORD=apwnZOXN*
ENV MYSQL_DATABASE=formationnoobdocker

EXPOSE 3306 33060
